# Generated by Django 4.1 on 2023-02-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sProductNr", models.CharField(max_length=20)),
                ("sProductNm", models.CharField(max_length=100)),
                ("sProductPrice", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sProductDescription", models.CharField(max_length=15)),
                (
                    "sImagePath",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
